// Code generated by "bitstringer -type=AuxFlags"; DO NOT EDIT

package perffile

import "strconv"

func (i AuxFlags) String() string {
	if i == 0 {
		return "0"
	}
	s := ""
	if i&AuxFlagCollision != 0 {
		s += "Collision|"
	}
	if i&AuxFlagOverwrite != 0 {
		s += "Overwrite|"
	}
	if i&AuxFlagPartial != 0 {
		s += "Partial|"
	}
	if i&AuxFlagTruncated != 0 {
		s += "Truncated|"
	}
	i &^= 15
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
