// Code generated by "stringer -type=AuxPMUFormat"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuxPMUFormatCoresightCoresight-0]
	_ = x[AuxPMUFormatCoresightRaw-1]
	_ = x[AuxPMUFormatDefault-0]
}

const _AuxPMUFormat_name = "AuxPMUFormatCoresightCoresightAuxPMUFormatCoresightRaw"

var _AuxPMUFormat_index = [...]uint8{0, 30, 54}

func (i AuxPMUFormat) String() string {
	if i >= AuxPMUFormat(len(_AuxPMUFormat_index)-1) {
		return "AuxPMUFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuxPMUFormat_name[_AuxPMUFormat_index[i]:_AuxPMUFormat_index[i+1]]
}
