// Code generated by "bitstringer -type=BranchFlags"; DO NOT EDIT

package perffile

import "strconv"

func (i BranchFlags) String() string {
	if i == 0 {
		return "0"
	}
	s := ""
	if i&BranchFlagAbort != 0 {
		s += "Abort|"
	}
	if i&BranchFlagInTransaction != 0 {
		s += "InTransaction|"
	}
	if i&BranchFlagMispredicted != 0 {
		s += "Mispredicted|"
	}
	if i&BranchFlagPredicted != 0 {
		s += "Predicted|"
	}
	i &^= 15
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
