// Code generated by "bitstringer -type=BreakpointOp"; DO NOT EDIT

package perffile

import "strconv"

func (i BreakpointOp) String() string {
	if i == 0 {
		return "0"
	}
	s := ""
	if i&BreakpointOpR != 0 {
		s += "R|"
	}
	if i&BreakpointOpRW != 0 {
		s += "RW|"
	}
	i &^= 3
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
