// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type=CPUMode; DO NOT EDIT

package perffile

import "fmt"

const _CPUMode_name = "CPUModeUnknownCPUModeKernelCPUModeUserCPUModeHypervisorCPUModeGuestKernelCPUModeGuestUser"

var _CPUMode_index = [...]uint8{0, 14, 27, 38, 55, 73, 89}

func (i CPUMode) String() string {
	if i+1 >= CPUMode(len(_CPUMode_index)) {
		return fmt.Sprintf("CPUMode(%d)", i)
	}
	return _CPUMode_name[_CPUMode_index[i]:_CPUMode_index[i+1]]
}
