// Code generated by "stringer -type=CPUMode"; DO NOT EDIT

package perffile

import "fmt"

const _CPUMode_name = "CPUModeUnknownCPUModeKernelCPUModeUserCPUModeHypervisorCPUModeGuestKernelCPUModeGuestUser"

var _CPUMode_index = [...]uint8{0, 14, 27, 38, 55, 73, 89}

func (i CPUMode) String() string {
	if i >= CPUMode(len(_CPUMode_index)-1) {
		return fmt.Sprintf("CPUMode(%d)", i)
	}
	return _CPUMode_name[_CPUMode_index[i]:_CPUMode_index[i+1]]
}
