// Code generated by "stringer -type=CPUMode"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CPUModeUnknown-0]
	_ = x[CPUModeKernel-1]
	_ = x[CPUModeUser-2]
	_ = x[CPUModeHypervisor-3]
	_ = x[CPUModeGuestKernel-4]
	_ = x[CPUModeGuestUser-5]
}

const _CPUMode_name = "CPUModeUnknownCPUModeKernelCPUModeUserCPUModeHypervisorCPUModeGuestKernelCPUModeGuestUser"

var _CPUMode_index = [...]uint8{0, 14, 27, 38, 55, 73, 89}

func (i CPUMode) String() string {
	if i >= CPUMode(len(_CPUMode_index)-1) {
		return "CPUMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CPUMode_name[_CPUMode_index[i]:_CPUMode_index[i+1]]
}
