// Code generated by "stringer -type=DataSrcLevelNum"; DO NOT EDIT.

package perffile

import "strconv"

const _DataSrcLevelNum_name = "DataSrcLevelNumL1"

var _DataSrcLevelNum_index = [...]uint8{0, 17}

func (i DataSrcLevelNum) String() string {
	i -= 1
	if i < 0 || i >= DataSrcLevelNum(len(_DataSrcLevelNum_index)-1) {
		return "DataSrcLevelNum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataSrcLevelNum_name[_DataSrcLevelNum_index[i]:_DataSrcLevelNum_index[i+1]]
}
