// Code generated by "bitstringer -type=DataSrcSnoop"; DO NOT EDIT

package perffile

import "strconv"

func (i DataSrcSnoop) String() string {
	if i == 0 {
		return "NA"
	}
	s := ""
	if i&DataSrcSnoopFwd != 0 {
		s += "Fwd|"
	}
	if i&DataSrcSnoopHit != 0 {
		s += "Hit|"
	}
	if i&DataSrcSnoopHitM != 0 {
		s += "HitM|"
	}
	if i&DataSrcSnoopMiss != 0 {
		s += "Miss|"
	}
	if i&DataSrcSnoopNone != 0 {
		s += "None|"
	}
	i &^= 31
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}