// Code generated by "stringer -type=DataSrcLock"; DO NOT EDIT

package perffile

import "fmt"

const _DataSrcLock_name = "DataSrcLockNADataSrcLockUnlockedDataSrcLockLocked"

var _DataSrcLock_index = [...]uint8{0, 13, 32, 49}

func (i DataSrcLock) String() string {
	if i < 0 || i >= DataSrcLock(len(_DataSrcLock_index)-1) {
		return fmt.Sprintf("DataSrcLock(%d)", i)
	}
	return _DataSrcLock_name[_DataSrcLock_index[i]:_DataSrcLock_index[i+1]]
}
