// Code generated by "stringer -type=DataSrcLock"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataSrcLockNA-0]
	_ = x[DataSrcLockUnlocked-1]
	_ = x[DataSrcLockLocked-2]
}

const _DataSrcLock_name = "DataSrcLockNADataSrcLockUnlockedDataSrcLockLocked"

var _DataSrcLock_index = [...]uint8{0, 13, 32, 49}

func (i DataSrcLock) String() string {
	if i < 0 || i >= DataSrcLock(len(_DataSrcLock_index)-1) {
		return "DataSrcLock(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSrcLock_name[_DataSrcLock_index[i]:_DataSrcLock_index[i+1]]
}
