// Code generated by "bitstringer -type=DataSrcBlock"; DO NOT EDIT

package perffile

import "strconv"

func (i DataSrcBlock) String() string {
	if i == 0 {
		return "NA"
	}
	s := ""
	if i&DataSrcBlockAddr != 0 {
		s += "Addr|"
	}
	if i&DataSrcBlockData != 0 {
		s += "Data|"
	}
	i &^= 3
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
