// Code generated by "stringer -type=DataSrcHops"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataSrcHopsCore-1]
	_ = x[DataSrcHopsNode-3]
	_ = x[DataSrcHopsSocket-3]
	_ = x[DataSrcHopesBoard-4]
	_ = x[DataSrcHopsNA-0]
}

const (
	_DataSrcHops_name_0 = "DataSrcHopsNADataSrcHopsCore"
	_DataSrcHops_name_1 = "DataSrcHopsNodeDataSrcHopesBoard"
)

var (
	_DataSrcHops_index_0 = [...]uint8{0, 13, 28}
	_DataSrcHops_index_1 = [...]uint8{0, 15, 32}
)

func (i DataSrcHops) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _DataSrcHops_name_0[_DataSrcHops_index_0[i]:_DataSrcHops_index_0[i+1]]
	case 3 <= i && i <= 4:
		i -= 3
		return _DataSrcHops_name_1[_DataSrcHops_index_1[i]:_DataSrcHops_index_1[i+1]]
	default:
		return "DataSrcHops(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
