// Code generated by "stringer -type=EventHardwareID,EventSoftware,HWCache,HWCacheOp,HWCacheResult"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventHardwareIDCPUCycles-0]
	_ = x[EventHardwareIDInstructions-1]
	_ = x[EventHardwareIDCacheReferences-2]
	_ = x[EventHardwareIDCacheMisses-3]
	_ = x[EventHardwareIDBranchInstructions-4]
	_ = x[EventHardwareIDBranchMisses-5]
	_ = x[EventHardwareIDBusCycles-6]
	_ = x[EventHardwareIDStalledCyclesFrontend-7]
	_ = x[EventHardwareIDStalledCyclesBackend-8]
	_ = x[EventHardwareIDRefCPUCycles-9]
}

const _EventHardwareID_name = "EventHardwareIDCPUCyclesEventHardwareIDInstructionsEventHardwareIDCacheReferencesEventHardwareIDCacheMissesEventHardwareIDBranchInstructionsEventHardwareIDBranchMissesEventHardwareIDBusCyclesEventHardwareIDStalledCyclesFrontendEventHardwareIDStalledCyclesBackendEventHardwareIDRefCPUCycles"

var _EventHardwareID_index = [...]uint16{0, 24, 51, 81, 107, 140, 167, 191, 227, 262, 289}

func (i EventHardwareID) String() string {
	if i >= EventHardwareID(len(_EventHardwareID_index)-1) {
		return "EventHardwareID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventHardwareID_name[_EventHardwareID_index[i]:_EventHardwareID_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventSoftwareCPUClock-0]
	_ = x[EventSoftwareTaskClock-1]
	_ = x[EventSoftwarePageFaults-2]
	_ = x[EventSoftwareContextSwitches-3]
	_ = x[EventSoftwareCPUMigrations-4]
	_ = x[EventSoftwarePageFaultsMin-5]
	_ = x[EventSoftwarePageFaultsMaj-6]
	_ = x[EventSoftwareAlignmentFaults-7]
	_ = x[EventSoftwareEmulationFaults-8]
	_ = x[EventSoftwareDummy-9]
	_ = x[EventSoftwareBpfOutput-10]
	_ = x[EventSoftwareCGroupSwitches-11]
}

const _EventSoftware_name = "EventSoftwareCPUClockEventSoftwareTaskClockEventSoftwarePageFaultsEventSoftwareContextSwitchesEventSoftwareCPUMigrationsEventSoftwarePageFaultsMinEventSoftwarePageFaultsMajEventSoftwareAlignmentFaultsEventSoftwareEmulationFaultsEventSoftwareDummyEventSoftwareBpfOutputEventSoftwareCGroupSwitches"

var _EventSoftware_index = [...]uint16{0, 21, 43, 66, 94, 120, 146, 172, 200, 228, 246, 268, 295}

func (i EventSoftware) String() string {
	if i >= EventSoftware(len(_EventSoftware_index)-1) {
		return "EventSoftware(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventSoftware_name[_EventSoftware_index[i]:_EventSoftware_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HWCacheL1D-0]
	_ = x[HWCacheL1I-1]
	_ = x[HWCacheLL-2]
	_ = x[HWCacheDTLB-3]
	_ = x[HWCacheITLB-4]
	_ = x[HWCacheBPU-5]
	_ = x[HWCacheNode-6]
}

const _HWCache_name = "HWCacheL1DHWCacheL1IHWCacheLLHWCacheDTLBHWCacheITLBHWCacheBPUHWCacheNode"

var _HWCache_index = [...]uint8{0, 10, 20, 29, 40, 51, 61, 72}

func (i HWCache) String() string {
	if i >= HWCache(len(_HWCache_index)-1) {
		return "HWCache(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCache_name[_HWCache_index[i]:_HWCache_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HWCacheOpRead-0]
	_ = x[HWCacheOpWrite-1]
	_ = x[HWCacheOpPrefetch-2]
}

const _HWCacheOp_name = "HWCacheOpReadHWCacheOpWriteHWCacheOpPrefetch"

var _HWCacheOp_index = [...]uint8{0, 13, 27, 44}

func (i HWCacheOp) String() string {
	if i >= HWCacheOp(len(_HWCacheOp_index)-1) {
		return "HWCacheOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheOp_name[_HWCacheOp_index[i]:_HWCacheOp_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HWCacheResultAccess-0]
	_ = x[HWCacheResultMiss-1]
}

const _HWCacheResult_name = "HWCacheResultAccessHWCacheResultMiss"

var _HWCacheResult_index = [...]uint8{0, 19, 36}

func (i HWCacheResult) String() string {
	if i >= HWCacheResult(len(_HWCacheResult_index)-1) {
		return "HWCacheResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheResult_name[_HWCacheResult_index[i]:_HWCacheResult_index[i+1]]
}
