// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type=EventPrecision; DO NOT EDIT

package perffile

import "fmt"

const _EventPrecision_name = "EventPrecisionArbitrarySkidEventPrecisionConstantSkidEventPrecisionTryZeroSkidEventPrecisionZeroSkip"

var _EventPrecision_index = [...]uint8{0, 27, 53, 78, 100}

func (i EventPrecision) String() string {
	if i < 0 || i+1 >= EventPrecision(len(_EventPrecision_index)) {
		return fmt.Sprintf("EventPrecision(%d)", i)
	}
	return _EventPrecision_name[_EventPrecision_index[i]:_EventPrecision_index[i+1]]
}
