// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type=EventClass; DO NOT EDIT

package perffile

import "fmt"

const _EventClass_name = "EventClassHardwareEventClassSoftwareEventClassTracepointEventClassHWCacheEventClassRawEventClassBreakpoint"

var _EventClass_index = [...]uint8{0, 18, 36, 56, 73, 86, 106}

func (i EventClass) String() string {
	if i+1 >= EventClass(len(_EventClass_index)) {
		return fmt.Sprintf("EventClass(%d)", i)
	}
	return _EventClass_name[_EventClass_index[i]:_EventClass_index[i+1]]
}
