// Code generated by "stringer -type=EventPrecision"; DO NOT EDIT

package perffile

import "fmt"

const _EventPrecision_name = "EventPrecisionArbitrarySkidEventPrecisionConstantSkidEventPrecisionTryZeroSkidEventPrecisionZeroSkip"

var _EventPrecision_index = [...]uint8{0, 27, 53, 78, 100}

func (i EventPrecision) String() string {
	if i < 0 || i >= EventPrecision(len(_EventPrecision_index)-1) {
		return fmt.Sprintf("EventPrecision(%d)", i)
	}
	return _EventPrecision_name[_EventPrecision_index[i]:_EventPrecision_index[i+1]]
}
