// Code generated by "stringer -type=EventHardware,EventSoftware,HWCache,HWCacheOp,HWCacheResult"; DO NOT EDIT.

package perffile

import "strconv"

const _EventHardware_name = "EventHardwareCPUCyclesEventHardwareInstructionsEventHardwareCacheReferencesEventHardwareCacheMissesEventHardwareBranchInstructionsEventHardwareBranchMissesEventHardwareBusCyclesEventHardwareStalledCyclesFrontendEventHardwareStalledCyclesBackendEventHardwareRefCPUCycles"

var _EventHardware_index = [...]uint16{0, 22, 47, 75, 99, 130, 155, 177, 211, 244, 269}

func (i EventHardware) String() string {
	if i >= EventHardware(len(_EventHardware_index)-1) {
		return "EventHardware(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventHardware_name[_EventHardware_index[i]:_EventHardware_index[i+1]]
}

const _EventSoftware_name = "EventSoftwareCPUClockEventSoftwareTaskClockEventSoftwarePageFaultsEventSoftwareContextSwitchesEventSoftwareCPUMigrationsEventSoftwarePageFaultsMinEventSoftwarePageFaultsMajEventSoftwareAlignmentFaultsEventSoftwareEmulationFaultsEventSoftwareDummyEventSoftwareBpfOutput"

var _EventSoftware_index = [...]uint16{0, 21, 43, 66, 94, 120, 146, 172, 200, 228, 246, 268}

func (i EventSoftware) String() string {
	if i >= EventSoftware(len(_EventSoftware_index)-1) {
		return "EventSoftware(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventSoftware_name[_EventSoftware_index[i]:_EventSoftware_index[i+1]]
}

const _HWCache_name = "HWCacheL1DHWCacheL1IHWCacheLLHWCacheDTLBHWCacheITLBHWCacheBPUHWCacheNode"

var _HWCache_index = [...]uint8{0, 10, 20, 29, 40, 51, 61, 72}

func (i HWCache) String() string {
	if i >= HWCache(len(_HWCache_index)-1) {
		return "HWCache(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCache_name[_HWCache_index[i]:_HWCache_index[i+1]]
}

const _HWCacheOp_name = "HWCacheOpReadHWCacheOpWriteHWCacheOpPrefetch"

var _HWCacheOp_index = [...]uint8{0, 13, 27, 44}

func (i HWCacheOp) String() string {
	if i >= HWCacheOp(len(_HWCacheOp_index)-1) {
		return "HWCacheOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheOp_name[_HWCacheOp_index[i]:_HWCacheOp_index[i+1]]
}

const _HWCacheResult_name = "HWCacheResultAccessHWCacheResultMiss"

var _HWCacheResult_index = [...]uint8{0, 19, 36}

func (i HWCacheResult) String() string {
	if i >= HWCacheResult(len(_HWCacheResult_index)-1) {
		return "HWCacheResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheResult_name[_HWCacheResult_index[i]:_HWCacheResult_index[i+1]]
}
