// Code generated by "stringer -type=EventPrecision"; DO NOT EDIT.

package perffile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventPrecisionArbitrarySkid-0]
	_ = x[EventPrecisionConstantSkid-1]
	_ = x[EventPrecisionTryZeroSkid-2]
	_ = x[EventPrecisionZeroSkip-3]
}

const _EventPrecision_name = "EventPrecisionArbitrarySkidEventPrecisionConstantSkidEventPrecisionTryZeroSkidEventPrecisionZeroSkip"

var _EventPrecision_index = [...]uint8{0, 27, 53, 78, 100}

func (i EventPrecision) String() string {
	if i < 0 || i >= EventPrecision(len(_EventPrecision_index)-1) {
		return "EventPrecision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventPrecision_name[_EventPrecision_index[i]:_EventPrecision_index[i+1]]
}
