// Code generated by "stringer -type=HWCacheOp"; DO NOT EDIT.

package perffile

import "strconv"

const _HWCacheOp_name = "HWCacheOpReadHWCacheOpWriteHWCacheOpPrefetch"

var _HWCacheOp_index = [...]uint8{0, 13, 27, 44}

func (i HWCacheOp) String() string {
	if i >= HWCacheOp(len(_HWCacheOp_index)-1) {
		return "HWCacheOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheOp_name[_HWCacheOp_index[i]:_HWCacheOp_index[i+1]]
}
