// Code generated by "stringer -type=HWCacheResult"; DO NOT EDIT.

package perffile

import "strconv"

const _HWCacheResult_name = "HWCacheResultAccessHWCacheResultMiss"

var _HWCacheResult_index = [...]uint8{0, 19, 36}

func (i HWCacheResult) String() string {
	if i >= HWCacheResult(len(_HWCacheResult_index)-1) {
		return "HWCacheResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HWCacheResult_name[_HWCacheResult_index[i]:_HWCacheResult_index[i+1]]
}
