// Code generated by "bitstringer -type=KsymbolType"; DO NOT EDIT

package perffile

import "strconv"

func (i KsymbolType) String() string {
	if i == 0 {
		return "Unknown"
	}
	s := ""
	if i&KsymbolTypeBpf != 0 {
		s += "Bpf|"
	}
	if i&KsymbolTypeOol != 0 {
		s += "Ool|"
	}
	i &^= 3
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
