// Code generated by "bitstringer -type=KsymbolFlags"; DO NOT EDIT

package perffile

import "strconv"

func (i KsymbolFlags) String() string {
	if i == 0 {
		return "Unregister"
	}
	s := ""
	i &^= 0
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
