// Code generated by "bitstringer -type=ReadFormat"; DO NOT EDIT

package perffile

import "strconv"

func (i ReadFormat) String() string {
	if i == 0 {
		return "0"
	}
	s := ""
	if i&ReadFormatGroup != 0 {
		s += "Group|"
	}
	if i&ReadFormatID != 0 {
		s += "ID|"
	}
	if i&ReadFormatTotalTimeEnabled != 0 {
		s += "TotalTimeEnabled|"
	}
	if i&ReadFormatTotalTimeRunning != 0 {
		s += "TotalTimeRunning|"
	}
	i &^= 15
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}