// Code generated by "stringer -type=RecordsOrder"; DO NOT EDIT

package perffile

import "fmt"

const _RecordsOrder_name = "RecordsFileOrderRecordsCausalOrderRecordsTimeOrder"

var _RecordsOrder_index = [...]uint8{0, 16, 34, 50}

func (i RecordsOrder) String() string {
	if i < 0 || i >= RecordsOrder(len(_RecordsOrder_index)-1) {
		return fmt.Sprintf("RecordsOrder(%d)", i)
	}
	return _RecordsOrder_name[_RecordsOrder_index[i]:_RecordsOrder_index[i+1]]
}
