// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// generated by stringer -type=SampleRegsABI; DO NOT EDIT

package perffile

import "fmt"

const _SampleRegsABI_name = "SampleRegsABINoneSampleRegsABI32SampleRegsABI64"

var _SampleRegsABI_index = [...]uint8{0, 17, 32, 47}

func (i SampleRegsABI) String() string {
	if i+1 >= SampleRegsABI(len(_SampleRegsABI_index)) {
		return fmt.Sprintf("SampleRegsABI(%d)", i)
	}
	return _SampleRegsABI_name[_SampleRegsABI_index[i]:_SampleRegsABI_index[i+1]]
}
