// Code generated by "bitstringer -type=Transaction"; DO NOT EDIT

package perffile

import "strconv"

func (i Transaction) String() string {
	if i == 0 {
		return "0"
	}
	s := ""
	if i&TransactionAsync != 0 {
		s += "Async|"
	}
	if i&TransactionCapacityRead != 0 {
		s += "CapacityRead|"
	}
	if i&TransactionCapacityWrite != 0 {
		s += "CapacityWrite|"
	}
	if i&TransactionConflict != 0 {
		s += "Conflict|"
	}
	if i&TransactionElision != 0 {
		s += "Elision|"
	}
	if i&TransactionRetry != 0 {
		s += "Retry|"
	}
	if i&TransactionSync != 0 {
		s += "Sync|"
	}
	if i&TransactionTransaction != 0 {
		s += "Transaction|"
	}
	i &^= 255
	if i == 0 {
		return s[:len(s)-1]
	}
	return s + "0x" + strconv.FormatUint(uint64(i), 16)
}
